"""initial schema

Revision ID: d954d9a49510
Revises: 
Create Date: 2026-03-28 17:50:38.084150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd954d9a49510'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('providers',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('api_base_url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_providers'))
    )
    op.create_index(op.f('ix_providers_slug'), 'providers', ['slug'], unique=True)
    op.create_table('llm_models',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('external_model_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('routing_key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('supports_json', sa.Boolean(), nullable=False),
    sa.Column('supports_tools', sa.Boolean(), nullable=False),
    sa.Column('supports_vision', sa.Boolean(), nullable=False),
    sa.Column('tier', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('context_window', sa.Integer(), nullable=True),
    sa.Column('max_output_tokens', sa.Integer(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], name=op.f('fk_llm_models_provider_id_providers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_models')),
    sa.UniqueConstraint('provider_id', 'external_model_id', name=op.f('uq_llm_models_provider_id')),
    sa.UniqueConstraint('routing_key', name=op.f('uq_llm_models_routing_key'))
    )
    op.create_index(op.f('ix_llm_models_provider_id'), 'llm_models', ['provider_id'], unique=False)
    op.create_table('provider_sync_runs',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('models_found', sa.Integer(), nullable=False),
    sa.Column('models_updated', sa.Integer(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], name=op.f('fk_provider_sync_runs_provider_id_providers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_sync_runs'))
    )
    op.create_index(op.f('ix_provider_sync_runs_provider_id'), 'provider_sync_runs', ['provider_id'], unique=False)
    op.create_table('llm_model_capabilities',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('capability', sa.Enum('GENERAL', 'ANALYSIS', 'CODE', 'CREATIVE', 'JSON', name='capability', native_enum=False), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['llm_models.id'], name=op.f('fk_llm_model_capabilities_model_id_llm_models')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_model_capabilities')),
    sa.UniqueConstraint('model_id', 'capability', name=op.f('uq_llm_model_capabilities_model_id'))
    )
    op.create_index(op.f('ix_llm_model_capabilities_model_id'), 'llm_model_capabilities', ['model_id'], unique=False)
    op.create_table('llm_model_routing_settings',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('quality_score', sa.Integer(), nullable=False),
    sa.Column('latency_score', sa.Integer(), nullable=False),
    sa.Column('cost_score', sa.Integer(), nullable=False),
    sa.Column('default_temperature', sa.Float(), nullable=False),
    sa.Column('priority_weight', sa.Integer(), nullable=False),
    sa.Column('allow_fallback', sa.Boolean(), nullable=False),
    sa.Column('enabled_for_routing', sa.Boolean(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['llm_models.id'], name=op.f('fk_llm_model_routing_settings_model_id_llm_models')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_model_routing_settings')),
    sa.UniqueConstraint('model_id', name=op.f('uq_llm_model_routing_settings_model_id'))
    )
    op.create_table('llm_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('intent', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('priority', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('require_json', sa.Boolean(), nullable=False),
    sa.Column('selected_model_id', sa.Integer(), nullable=True),
    sa.Column('fallback_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['selected_model_id'], ['llm_models.id'], name=op.f('fk_llm_requests_selected_model_id_llm_models'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_requests'))
    )
    op.create_index(op.f('ix_llm_requests_selected_model_id'), 'llm_requests', ['selected_model_id'], unique=False)
    op.create_table('llm_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('provider_slug', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('model_routing_key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('attempt_order', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['llm_requests.id'], name=op.f('fk_llm_attempts_request_id_llm_requests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_attempts'))
    )
    op.create_index(op.f('ix_llm_attempts_request_id'), 'llm_attempts', ['request_id'], unique=False)
    op.create_table('llm_executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Float(), server_default='0', nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['llm_models.id'], name=op.f('fk_llm_executions_model_id_llm_models'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['request_id'], ['llm_requests.id'], name=op.f('fk_llm_executions_request_id_llm_requests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_executions'))
    )
    op.create_index(op.f('ix_llm_executions_model_id'), 'llm_executions', ['model_id'], unique=False)
    op.create_index(op.f('ix_llm_executions_request_id'), 'llm_executions', ['request_id'], unique=False)
    op.create_table('llm_feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['llm_models.id'], name=op.f('fk_llm_feedback_model_id_llm_models'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['request_id'], ['llm_requests.id'], name=op.f('fk_llm_feedback_request_id_llm_requests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_feedback'))
    )
    op.create_index(op.f('ix_llm_feedback_model_id'), 'llm_feedback', ['model_id'], unique=False)
    op.create_index(op.f('ix_llm_feedback_request_id'), 'llm_feedback', ['request_id'], unique=False)
    op.create_table('model_evaluations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('latency_score', sa.Float(), nullable=False),
    sa.Column('cost_score', sa.Float(), nullable=False),
    sa.Column('final_score', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('pros', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('cons', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['llm_models.id'], name=op.f('fk_model_evaluations_model_id_llm_models'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['request_id'], ['llm_requests.id'], name=op.f('fk_model_evaluations_request_id_llm_requests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_evaluations'))
    )
    op.create_index(op.f('ix_model_evaluations_model_id'), 'model_evaluations', ['model_id'], unique=False)
    op.create_index(op.f('ix_model_evaluations_request_id'), 'model_evaluations', ['request_id'], unique=False)
    op.create_table('request_analysis',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('task_type', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('complexity_score', sa.Float(), nullable=False),
    sa.Column('cost_sensitivity', sa.Float(), nullable=False),
    sa.Column('latency_sensitivity', sa.Float(), nullable=False),
    sa.Column('detected_skills', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('tokens_estimated', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['llm_requests.id'], name=op.f('fk_request_analysis_request_id_llm_requests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_request_analysis'))
    )
    op.create_index(op.f('ix_request_analysis_request_id'), 'request_analysis', ['request_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_request_analysis_request_id'), table_name='request_analysis')
    op.drop_table('request_analysis')
    op.drop_index(op.f('ix_model_evaluations_request_id'), table_name='model_evaluations')
    op.drop_index(op.f('ix_model_evaluations_model_id'), table_name='model_evaluations')
    op.drop_table('model_evaluations')
    op.drop_index(op.f('ix_llm_feedback_request_id'), table_name='llm_feedback')
    op.drop_index(op.f('ix_llm_feedback_model_id'), table_name='llm_feedback')
    op.drop_table('llm_feedback')
    op.drop_index(op.f('ix_llm_executions_request_id'), table_name='llm_executions')
    op.drop_index(op.f('ix_llm_executions_model_id'), table_name='llm_executions')
    op.drop_table('llm_executions')
    op.drop_index(op.f('ix_llm_attempts_request_id'), table_name='llm_attempts')
    op.drop_table('llm_attempts')
    op.drop_index(op.f('ix_llm_requests_selected_model_id'), table_name='llm_requests')
    op.drop_table('llm_requests')
    op.drop_table('llm_model_routing_settings')
    op.drop_index(op.f('ix_llm_model_capabilities_model_id'), table_name='llm_model_capabilities')
    op.drop_table('llm_model_capabilities')
    op.drop_index(op.f('ix_provider_sync_runs_provider_id'), table_name='provider_sync_runs')
    op.drop_table('provider_sync_runs')
    op.drop_index(op.f('ix_llm_models_provider_id'), table_name='llm_models')
    op.drop_table('llm_models')
    op.drop_index(op.f('ix_providers_slug'), table_name='providers')
    op.drop_table('providers')
    # ### end Alembic commands ###
